config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  get 'moadda/:username',to: "profile#show",as: "instagram_profile"
  post 'profile_image',to: "profile#image"
  post 'photo_post',to: "posts#create_post"
 
  get 'users_profile/:id',to: "users#profile",as: "users_profile"
  post 'follow',to: "users#follow"
  post 'unfollow',to: "users#unfollow"
 
  post 'comments',to: "comments#create"

  get "post/:id", to: "posts#find_post"

  get "", to: "home#index",as: "home"
  get "search_user", to: "search#users"

  post "likes",to: "likes#create_like"
  post "unlike", to: "likes#unlike"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def users
    @users = User.all
    @current_user_followings = current_user.following_users
    
    if params[:search].present? && params[:search].length >= 3

      @users = @users.where("lower(username) LIKE ?", "%#{params[:search]}%" )
    else
      redirect_to root_url
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/users.html.erb
<section class="container container-top">
  <div class = "search_section">
    <% @users.each do |user| %>
      <div class = "search_profile">
        <%= link_to (users_profile_path(user)),class: "search_user" do %>
          <% if user.avatar.attached? %>
            <%= image_tag url_for(user.avatar),class: "search_image" %>
          <% else %>

            <svg viewBox="0 0 16 16" class= "search_image" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
              <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
              <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
            </svg>
            
          <% end %>

          <span class = search_username><%= user.username %></span>
        <% end %>
        <div class = "search_follow_link">
          <% if @current_user_followings.include?(user) %>

            <%= link_to "unfollow",unfollow_path(following_id: user.id),class: "search_user_unfollow" %>

          <% else %>

            <%= link_to "follow",follow_path(following_id: user.id),class: "search_user_follow" %>

          <% end %>
        </div>
      </div>
      
    <% end %>
  </div>


  <script>
    $("body").on("click", ".search_user_follow", function(event){
      event.preventDefault();
      var follow = $(event.target);

      $.ajax({

        url: follow.attr('href'),
        
        method: "POST",
        dataType: "json",
        
        success: function(followdata){
          if(followdata.success === true) {
            var follow_parent = $(follow).parent("div");
            $(follow).destroy;

            var unfollow_link = "<a href= '" + "/unfollow?following_id=" + followdata.following_id + "' class= 'search_user_unfollow' >" + "unfollow" + "</a>"
            $(follow_parent).html(unfollow_link)
          }

        }
      })
      
    })


    $("body").on("click", ".search_user_unfollow", function(event){
      event.preventDefault();
      var unfollow = $(event.target);

      $.ajax({
        url: unfollow.attr('href'),
        method: "POST",
        dataType: "json",

        success: function(unfollowdata) {
          if(unfollowdata.success === true) {
            var unfollow_parent = $(unfollow).parent("div");
            $(unfollow).destroy;

            var follow_link = "<a href= '" + "/follow?following_id=" + unfollowdata.following_id + "' class= 'search_user_follow' >" + "follow" + "</a>"

            
            $(unfollow_parent).html(follow_link)
          }           
        }
      })
      
    })
  </script>
</section>