config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  get 'moadda/:username',to: "profile#show",as: "instagram_profile"
  post 'profile_image',to: "profile#image"
  post 'photo_post',to: "posts#create_post"
 
  get 'users_profile/:id',to: "users#profile",as: "users_profile"
  post 'follow',to: "users#follow"
  post 'unfollow',to: "users#unfollow"
 
  post 'comments',to: "comments#create"

  get "post/:id", to: "posts#find_post"

  get "", to: "home#index",as: "home"
  get "search_user", to: "search#users"

  post "likes",to: "likes#create_like"
  post "unlike", to: "likes#unlike"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :following_user, class_name: 'User', foreign_key: 'following_id'
  belongs_to :follower_user, class_name: 'User', foreign_key: 'follower_id'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image,dependent: :destroy


  def as_json(options = {})
    image = Rails.application.routes.url_helpers.rails_blob_path(self.image, only_path: true)
    super(options).merge({image_url: image})
  end

  
  def liked(user_id)
    Like.where(user_id: user_id,post_id: self.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :username, presence: true , format: {with: /\A[a-z._]+[0-9]*\Z/}, length: {in: 3..25}

  has_one_attached :avatar, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :followings, class_name: "Follow", foreign_key: :follower_id, dependent: :destroy
  has_many :following_users, through: :followings


  has_many :followers, class_name: "Follow", foreign_key: :following_id, dependent: :destroy
  has_many :follower_users, through: :followers

  has_many :timeline_posts, through: :following_users,source: :posts


  def serializable_hash(options = {})
    if self.avatar.attached?
      avatar_url = Rails.application.routes.url_helpers.rails_blob_path(self.avatar, only_path: true)
      super(options).tap do |hash|
        hash["avatar_url"] = avatar_url
      end
    else
      super({})
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:comment][:post_id])
    @comments = @post.comments.build(comment_params)
   
    @comments.user_id = current_user.id

    if @comments.save
      render json: {success: true,comment: @comments.as_json(include: {user: {except: :avatar}} )}
    else
      render root_url 
    end
  end



  private


  def comment_params
    params.require(:comment).permit(:text,:post_id,:user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  LIMITS_PER_PAGE = 10

  def index
    @posts = current_user.timeline_posts.includes(:user,:likes,comments: [:user])
    @page = (params[:page] || 1).to_i
    @rows = @posts.count
    @total_pages = (@rows / LIMITS_PER_PAGE).ceil
    @posts = @posts.order(created_at: :desc).offset((@page - 1) * LIMITS_PER_PAGE).limit(LIMITS_PER_PAGE)

    if request.format.json?
      html_str = ''
      @posts.each do |home_post|
        html_str += render_to_string(partial: "post",locals: {home_post: home_post},layout: false)
      end
    end

    respond_to do |format|
      format.html
      format.json { render json: {success: true, post: html_str.html_safe} }
    end

  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create_like

    if Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
      render json: {success: false,error: "you have already liked this post"}
    else
      @like = Like.new(like_params)
      @like.user_id = current_user.id
      
      if @like.save
        render json: {success: true}
      else
        render json: {success: false, error: @like.errors.full_messages}
      end
    end
  end

  def unlike
    if Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
      @unlike = Like.where(user_id: current_user.id, post_id: params[:post_id]).first.destroy
  
      render json: {success: true}
    else
      render json: {success: false}
    end
    
  end


  private

  def like_params
    params.permit(:user_id,:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  

  def create_post
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to instagram_profile_path(current_user.username)
    else
      render profile_image_path
    end
  end


  def find_post
    @post = Post.includes(comments: :user).find(params[:id])
    data = @post.as_json(include: { comments: { include: :user}})
    if @post.user.avatar.attached? 
      data[:user] = {username: @post.user.username, avatar_url: Rails.application.routes.url_helpers.rails_blob_path(@post.user.avatar, only_path: true)}
    else
      data[:user] = {username: @post.user.username}
    end
    render json: data
  end

  private

  def post_params
    params.permit(:image,:caption)
  end 
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!

  def show
    @current_user_followers = current_user.follower_users
    @current_user_followings = current_user.following_users
    @posts = current_user.posts

    #@all_comments = Post.first.comments.includes(:user) 
  end

  def image
    if current_user.update(avatar: params[:avatar])
      redirect_to instagram_profile_path(current_user.username)
    else
      redirect_to instagram_profile_path(current_user.username)
    end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def users
    @users = User.all
    @current_user_followings = current_user.following_users
    
    if params[:search].present? && params[:search].length >= 3

      @users = @users.where("lower(username) LIKE ?", "%#{params[:search]}%" )
    else
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def profile
    @user = User.find(params[:id])
    @follow = Follow.where(follower_id: current_user.id ,following_id: params[:id])
    @followers = @user.follower_users
    @followings = @user.following_users
    @current_user_followings = current_user.following_users
    @other_user_posts = @user.posts
    #@all_comments = Post.first.comments.includes(:user)
  end

   def follow
    if params[:following_id].to_i == current_user.id
      render json: { success: false, error: "can't follow yourself" } and return
    end

    if Follow.where(follower_id: current_user.id, following_id: params[:following_id]).exists?
      render json: {success: false, error: "you have already followed this user"}
    else
      @follow = Follow.create(follower_id: current_user.id ,following_id: params[:following_id])
      #render json: @follow 
      render json: { success: true,following_id: params[:following_id] }
    end

  end

  def unfollow
    @unfollow = Follow.where(follower_id: current_user.id, following_id: params[:following_id]).first.destroy

    render json: {success: true,following_id: params[:following_id]}
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoAdda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav id="nav" class="nav">
      <div class="container d-flex align-items-center justify-content-between">
        <%= link_to (home_path) do %> 
          <%= image_tag "moadda.png",class: "nav_image" %>
        <% end %>   
        

        <%= form_tag search_user_path, method: :get do %>
          <%= search_field_tag :search , params[:search], placeholder: "Search atleast 3 character",autocapitalize: "none", class: "search" %>
        <% end %>

        
        <div class = "all_svg">

          <%= link_to (home_path) do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="navbar-icon home_page" viewBox="0 0 16 16">
              <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
            </svg>
          <% end %>

    
          <%= link_to (instagram_profile_path(current_user.username)) do %>
            <% if current_user.avatar.attached? %>
              <%= image_tag url_for(current_user.avatar),class: "svg_profile" %>
            <% else %>

              <svg viewBox="0 0 16 16" class= "svg_profile" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
                <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
              </svg>
            <% end %>
          <% end %>

          <svg width="1em" height="1em" viewBox="0 0 16 16" class="post_svg" data-toggle="modal" data-target="#exampleModal" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
            <title>create a post</title>
          </svg>

          <%= link_to (edit_user_registration_path) do %> 
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="settings" viewBox="0 0 16 16">
              <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"/>
              <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z"/>
            </svg>
          <% end %>
          <div class = "nav_logout">
            
            <%= link_to "log out",destroy_user_session_path,method: :delete %>
    
          </div>
        </div>
      </div>
    </nav>

  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">create a post</h5></br>
          
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_tag photo_post_path, multipart: true do %>
            <div class= "modal-title">
              <%= text_field_tag "caption" ,nil,placeholder: "write a caption" %>
            </div>
            <%= file_field_tag "image"%>
            <span class="modal-footer">
              <%= submit_tag "create post",class: "btn btn-primary" %>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </span>
          <% end %>
        </div>
        
      </div>
    </div>
  </div>

  <div class="modal fade" id="profileModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">change profile photo</h5></br>
          
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_tag profile_image_path, multipart: true do %>
            <%= file_field_tag "avatar" %>
            <span class="modal-footer">
            <%= submit_tag "change profile",class: "btn btn-primary" %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </span>
          <% end %>
        </div>
        
      </div>
    </div>
  </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>devise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_post_modal.html.erb
<div class="modal fade" id="full_user_post" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog full_modal" role="document">
    <div class="modal-content">
      
      <div class="modal-body post_body">
        
        <div id="post_image">
          
        </div>
        
        <div class = "comments">

          <div class = "caption_section">
            
          </div>

          <div class = "comment_section">

            

          </div>

          <div class = "modal_comment">
            <%= form_for Comment.new ,html: { class: "all_modal_comment" } do |comment| %>
            
              <%= comment.text_field :text ,placeholder: "Add a comment..." ,class: "add_modal_comment" %>
              <%= comment.hidden_field :post_id, :value => "" %>
              
              <%= comment.submit "post",class: "post-comment-btn" %>
              
            <% end %>
          </div>
        </div>
      
        
      </div>

    </div>
  </div>
</div>



  <script>
    $('#full_user_post').on('show.bs.modal', function (event) {
      var post = $(event.relatedTarget) // Button that triggered the modal
      var post_id = post.data('post-id') // Extract info from data-* attributes
      var modal = $(this)

      $.ajax({
        url: "/post/" + post_id,
        success: function (data) {
          updateModal(modal, data,post_id)
        }
      })
      // modal.find('.modal-title').text('New message to ' + recipient)
      // modal.find('.modal-body input').val(recipient)
    })

    function updateModal(modal, data,post_id) {
      image = "<img src='" + data.image_url + "' width='512' height='400'>"
      post_user = ""
      if (data.user.avatar_url) {
        post_user += "<img src='" + data.user.avatar_url + "' class = comment_profile >"
      }
      else {
          post_user += "<svg viewBox='0 0 16 16' class= 'comment_profile' fill='currentColor' xmlns='http://www.w3.org/2000/svg'>"+"<path d='M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z'/>"+"<path fill-rule='evenodd' d='M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z'/>"+"<path fill-rule='evenodd' d='M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z'/>"+"</svg>"
      }
      post_user += "<a href = '/users_profile/" + data.user.id + "'"+"class = 'post-comment-author'"+ ">" + data.user.username + "</a>"+ "<span class = 'comments_text'>" + data.caption + "</span>"

      
      
      $("#comment_post_id").val(post_id);
     

      other_user_comments = ""
      for (i = 0; i < data.comments.length; i++) {

        other_user_comments += "<div class = 'comment_div'>"
        if (data.comments[i].user.avatar_url) {
         other_user_comments += "<img src='" + data.comments[i].user.avatar_url + "' class = comment_profile >" }
        else {
          other_user_comments += "<svg viewBox='0 0 16 16' class= 'comment_profile' fill='currentColor' xmlns='http://www.w3.org/2000/svg'>"+"<path d='M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z'/>"+"<path fill-rule='evenodd' d='M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z'/>"+"<path fill-rule='evenodd' d='M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z'/>"+"</svg>"
        }

        other_user_comments += "<a href = '/users_profile/" + data.comments[i].user.id + "'"+"class = 'post-comment-author'"+ ">" + data.comments[i].user.username +"</a>"+ "<span class = 'comments_text'>"+ data.comments[i].text + "</span>"+ "</div>"
        
      }
"<span class = 'comments_text'>" + 
      
      
      $('#post_image').html(image)
      $('.caption_section').html(post_user)
      $('.comment_section').html(other_user_comments)
       
    }



    $(".post-comment-btn").on("click", function(event){
      var comment_post_btn = $(event.target);
      var comment_form = $(comment_post_btn).parent(".all_modal_comment")
      event.preventDefault();
     
      
      $.ajax({
        url: "/comments",
        method: "POST",
        data: comment_form.serialize(),
        dataType: "json",
        success: function(comment_data){
          if(comment_data.success === true) {
            comment_text = ""
            comment_text += "<div class = 'comment_div' >"
            if (comment_data.comment.user.avatar_url) {
              comment_text += "<img src= '"+ comment_data.comment.user.avatar_url +"' class = comment_profile >" }
            else {
              comment_text += "<svg viewBox='0 0 16 16' class= 'comment_profile' fill='currentColor' xmlns='http://www.w3.org/2000/svg'>"+"<path d='M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z'/>"+"<path fill-rule='evenodd' d='M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z'/>"+"<path fill-rule='evenodd' d='M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z'/>"+"</svg>"
            }
            comment_text += "<a href = '/users_profile/" + comment_data.comment.user.id + "'"+"class = 'post-comment-author'"+ ">" + comment_data.comment.user.username + "</a>"+ "<span class = 'comments_text'>" + comment_data.comment.text + "</span>"+ "</div>"
            $(".comment_section").append(comment_text);
            $(comment_form).children(".add_modal_comment").val("");
          }
        }
      })
    })
  </script>